public with sharing class questionController {
    /*public static string setNumber;
    @AuraEnabled(cacheable=true)
    public static void getSetNo(string setNum){
        setNumber=setNum;
        system.debug('Set number >> ' +setNumber);
    }
    @AuraEnabled(cacheable=true)
    public static List<question1__c> getQuestionList() {
        string temp=employeeController.setValue;
        system.debug('setNumber--' +temp);
        return [ SELECT Id, answer1__c, answer2__c, answer3__c, answer4__c, Name, Correct_answer__c, Type__c 
                FROM question1__c where RecordType.name = :temp];
    }*/
}